### ISSUE TITLE
Request: forge port? 

### ISSUE THREAD

**Issue by Blahaj-fanatic** [Hibiii/Blahaj#15]
This isn't an issue I'd just love if I could have Blahaj in my forge modpack. He is god

**Comment by hibiii** [comment]
no

i'd have to learn forge, a completely different ecosystem, not only that but i'd have to keep up with lex's insanity, and the only semblance of commonality, mixins, is broken on forge

unless you want an incredibly buggy port for a ludicrously outdated version of minecraft and forge...? (it might not be now but i bet $10 someone would be like "update forge port" in 2 years)
