### ISSUE TITLE
1.18.2 backport?

### ISSUE THREAD

**Issue by LordHungry** [Hibiii/Blahaj#3]
I'm not sure how much work it would be to backport it to 1.18.2, if it isn't much would it be possible?

I tried to backport it myself but Text.translatable and Allays aren't in the 1.18.2 quilt version from what I can see. Removing the tooltip function and AllayEntityMixin removed all the compiling errors but the game would crash on launch due to registry errors; not too much of a coder so that's as far as I got.

**Comment by LordHungry** [comment]
Nevermind about the registry errors I just get them when I build the jar file even for the regular version, I haven't used java in a hot minute so I might be doing something wrong lol

**Comment by LordHungry** [comment]
nvm abt it i just backported it i was being dumb ill open a PR incase you want it

**Comment by JieningYu** [comment]
It should be finished as the 1.18.2 version is compilable now.

**Comment by hibiii** [comment]
what 1.18.2 version? there's code for it right now but i haven't released it as a jar
